apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    deploymentId: {{ .Values.deploymentId }}
spec:
  project: default
  source:
    targetRevision: HEAD
    path: chart
    repoURL: "https://github.com/{{ .Values.org }}/{{ .Values.toRepo.name }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
