name: Build docs

on: push

jobs:
  build:
    name: Test chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: krateoplatformops/helm-values-validator-action@v1.0.2
        with:
          stop-if-find-orphans: false
